name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn prettier-check
      
      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
      
      - name: Build
        run: yarn build
        
        
